### ISSUE TITLE
playing the same sound multiple times not possible anymore

### ISSUE THREAD

**Issue by zocker-160** [amaitu/Empire-Earth-SoundBoard#13]
since commit 73abc251971f3a15cbf8682d07abce63f0ab9f3d it is no longer possible to play one sound multiple times at once, which was quite fun in order to "spam" the buttons :D

I think the introduction of the button play state is the problem, which does ignore further clicks as long as the state is on `active`

https://github.com/amaitu/Empire-Earth-SoundBoard/blob/73abc251971f3a15cbf8682d07abce63f0ab9f3d/src/components/SoundButton.vue#L41

It would be nice to be able to "spam" the Soudboard again ;) :D

**Comment by amaitu** [comment]
haha fair enough, I'll see if I can add that back in (;

**Comment by amaitu** [comment]
@zocker-160 fixed

**Comment by zocker-160** [comment]
@amaitu awesome :heart:
